Initial MPI implementation.  Work directory reorg.
MPI:  Loom and kg to sg flow parallel, but inbox consumption
still serialized.

diff --git a/Makefile.check b/Makefile.check
--- a/Makefile.check
+++ b/Makefile.check
@@ -8,8 +8,8 @@
 
 .PHONY: check debugcheck checkclean
 .PHONY: checkpart
-.PHONY: checkbucket checkbucket2 checkibucket checkiebucket checkciebucket
 .PHONY: checkflow debugflow benchflow
+.PHONY: checkflowmpi
 
 check: $(VELOUR)
 	@if [ -d "$(BASEDIR)/test" ] ; then \
@@ -28,51 +28,6 @@ checkpart: RUN=${PWD}/scripts/run-partitioning.sh
 checkpart: MINIK=9
 checkpart: PARTS=4
 checkpart: $(VELOUR)
-	@if [ -d "$(BASEDIR)/test" ] ; then \
-		$(MAKE) test -C "$(BASEDIR)/test" -f Makefile.test RUN=$(RUN) MINIK=$(MINIK) PARTS=$(PARTS) ; \
-		else echo "ERROR: test suite not present." && exit 1 ; \
-	fi
-
-checkbucket: RUN=${PWD}/scripts/run-bucket.sh
-checkbucket: MINIK=9
-checkbucket: PARTS=4
-checkbucket: $(VELOUR)
-	@if [ -d "$(BASEDIR)/test" ] ; then \
-		$(MAKE) test -C "$(BASEDIR)/test" -f Makefile.test RUN=$(RUN) MINIK=$(MINIK) PARTS=$(PARTS) ; \
-		else echo "ERROR: test suite not present." && exit 1 ; \
-	fi
-
-checkibucket: RUN=${PWD}/scripts/run-ibucket.sh
-checkibucket: MINIK=9
-checkibucket: PARTS=4
-checkibucket: $(VELOUR)
-	@if [ -d "$(BASEDIR)/test" ] ; then \
-		$(MAKE) test -C "$(BASEDIR)/test" -f Makefile.test RUN=$(RUN) MINIK=$(MINIK) PARTS=$(PARTS) ; \
-		else echo "ERROR: test suite not present." && exit 1 ; \
-	fi
-
-checkiebucket: RUN=${PWD}/scripts/run-iebucket.sh
-checkiebucket: MINIK=9
-checkiebucket: PARTS=4
-checkiebucket: $(VELOUR)
-	@if [ -d "$(BASEDIR)/test" ] ; then \
-		$(MAKE) test -C "$(BASEDIR)/test" -f Makefile.test RUN=$(RUN) MINIK=$(MINIK) PARTS=$(PARTS) ; \
-		else echo "ERROR: test suite not present." && exit 1 ; \
-	fi
-
-checkciebucket: RUN=${PWD}/scripts/run-ciebucket.sh
-checkciebucket: MINIK=18
-checkciebucket: PARTS=4
-checkciebucket: $(VELOUR)
-	@if [ -d "$(BASEDIR)/test" ] ; then \
-		$(MAKE) test -C "$(BASEDIR)/test" -f Makefile.test RUN=$(RUN) MINIK=$(MINIK) PARTS=$(PARTS) ; \
-		else echo "ERROR: test suite not present." && exit 1 ; \
-	fi
-
-checkbucket2: RUN=${PWD}/scripts/run-bucket2.sh
-checkbucket2: MINIK=9
-checkbucket2: PARTS=4
-checkbucket2: $(VELOUR)
 	@if [ -d "$(BASEDIR)/test" ] ; then \
 		$(MAKE) test -C "$(BASEDIR)/test" -f Makefile.test RUN=$(RUN) MINIK=$(MINIK) PARTS=$(PARTS) ; \
 		else echo "ERROR: test suite not present." && exit 1 ; \
@@ -105,6 +60,16 @@ benchflow: PARTS=4
 benchflow: OPTS="-mem 512"
 benchflow: VELOUR=$(VELOURBENCH)
 benchflow: $(VELOURBENCH)
+	@if [ -d "$(BASEDIR)/test" ] ; then \
+		$(MAKE) test -C "$(BASEDIR)/test" -f Makefile.test RUN=$(RUN) MINIK=$(MINIK) PARTS=$(PARTS) OPTS=$(OPTS) ; \
+		else echo "ERROR: test suite not present." && exit 1 ; \
+	fi
+
+checkflowmpi: RUN=${PWD}/scripts/run-flow-mpi.sh
+checkflowmpi: MINIK=9
+checkflowmpi: PARTS=4
+checkflowmpi: OPTS="-mem 512"
+checkflowmpi: $(VELOUR)
 	@if [ -d "$(BASEDIR)/test" ] ; then \
 		$(MAKE) test -C "$(BASEDIR)/test" -f Makefile.test RUN=$(RUN) MINIK=$(MINIK) PARTS=$(PARTS) OPTS=$(OPTS) ; \
 		else echo "ERROR: test suite not present." && exit 1 ; \
